In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
l=range(1000)
%timeit [i**2 for i in l]

The slowest run took 4.28 times longer than the fastest. This could mean that an intermediate result is being cached.
686 μs ± 317 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
a=np.arange(1000)
%timeit a**2

3.99 μs ± 1.33 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
a=np.array([1,2,3,4])

In [8]:
print(a.ndim)

1


In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)

2


In [12]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


In [14]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [16]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
print(np.diag(a))

[1 2 3 4]


##BASIC DATA TYPES

In [21]:
a=np.arange(10)
print(a.dtype)

int64


In [22]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [23]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## Other DataType

In [24]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [25]:
a=np.array([True,False])
print(a.dtype)

bool


In [26]:
a=np.array(['srue','alse'])
print(a.dtype)# unicode string type

<U4


## Indexing and Slicing

In [27]:
a=np.arange(10)
print(a[5])

5


In [28]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [29]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


## Slicing

In [31]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(a[1:8:2])

[1 3 5 7]


In [33]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

## Copies and Viewing

In [34]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [35]:
print(np.shares_memory(a,b))

True


In [36]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [37]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [38]:
print(np.shares_memory(a,b))

False


In [39]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


## Random Number Generator

In [40]:
a=np.random.randint(0,20,15)
print(a)

[ 1  7  7  3  4 14 13 18  3 18  0 11  0 16 10]


In [41]:
mask=(a%2==0)

In [42]:
mask_a=a[mask]
print(mask_a)

[ 4 14 18 18  0  0 16 10]


In [43]:
a[mask]=-1
print(a)

[ 1  7  7  3 -1 -1 13 -1  3 -1 -1 11 -1 -1 -1]


## Element wise Operations

## 1.Basic Operations

In [44]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [45]:
print(a**2)

[ 1  4  9 16]


## 2.Arithmetic Operations

In [46]:
b=np.ones(4)+1
print("a = ",a)
print("b = ",b)


a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [47]:
print(a*b)

[2. 4. 6. 8.]


In [48]:
print(a-b)

[-1.  0.  1.  2.]


In [49]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [50]:
print(c * c)
print("*********************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## 3.Comparision Operations

In [51]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [52]:
print(a<b)

[ True False  True False]


In [53]:
print(a>b)

[False False False False]


In [54]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [55]:
print(np.array_equal(a,c))

True


## 4.Logical Operations

In [56]:
a=np.array([1,0,1,0],dtype = "bool")
b=np.array([1,1,0,0],dtype = "bool")

In [57]:
print(np.logical_or(a,b))

[ True  True  True False]


In [58]:
print(np.logical_and(a,b))

[ True False False False]


## Trignometry and Transcendental Functions

In [59]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [60]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [61]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [62]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
